<?xml version = "1.0" ?>
<?xml:stylesheet type="text/xsl" href="SystemBOM.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW Address1 CDATA #IMPLIED>
  <!ATTLIST ROW Address2 CDATA #IMPLIED>
  <!ATTLIST ROW Address3 CDATA #IMPLIED>
  <!ATTLIST ROW Address4 CDATA #IMPLIED>
  <!ATTLIST ROW Application_BuildNumber CDATA #IMPLIED>
  <!ATTLIST ROW ApprovedBy CDATA #IMPLIED>
  <!ATTLIST ROW Author CDATA #IMPLIED>
  <!ATTLIST ROW CheckedBy CDATA #IMPLIED>
  <!ATTLIST ROW Code_IPC CDATA #IMPLIED>
  <!ATTLIST ROW Code_JEDEC CDATA #IMPLIED>
  <!ATTLIST ROW Comment CDATA #IMPLIED>
  <!ATTLIST ROW CompanyName CDATA #IMPLIED>
  <!ATTLIST ROW Component_Kind CDATA #IMPLIED>
  <!ATTLIST ROW ComponentKind CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink1Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink1URL CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink2Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink2URL CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink3Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink3URL CDATA #IMPLIED>
  <!ATTLIST ROW CompType CDATA #IMPLIED>
  <!ATTLIST ROW CurrentDate CDATA #IMPLIED>
  <!ATTLIST ROW CurrentTime CDATA #IMPLIED>
  <!ATTLIST ROW DatasheetDocument CDATA #IMPLIED>
  <!ATTLIST ROW DatasheetVersion CDATA #IMPLIED>
  <!ATTLIST ROW Date CDATA #IMPLIED>
  <!ATTLIST ROW Description CDATA #IMPLIED>
  <!ATTLIST ROW Designator CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW DesignItemId CDATA #IMPLIED>
  <!ATTLIST ROW Document CDATA #IMPLIED>
  <!ATTLIST ROW DocumentFullPathAndName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentNumber CDATA #IMPLIED>
  <!ATTLIST ROW DrawnBy CDATA #IMPLIED>
  <!ATTLIST ROW Engineer CDATA #IMPLIED>
  <!ATTLIST ROW Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Frequence CDATA #IMPLIED>
  <!ATTLIST ROW Height_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Height_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW Ibis_Model CDATA #IMPLIED>
  <!ATTLIST ROW ImagePath CDATA #IMPLIED>
  <!ATTLIST ROW Index CDATA #IMPLIED>
  <!ATTLIST ROW ItemGUID CDATA #IMPLIED>
  <!ATTLIST ROW LatestRevisionDate CDATA #IMPLIED>
  <!ATTLIST ROW LatestRevisionNote CDATA #IMPLIED>
  <!ATTLIST ROW Library_Name CDATA #IMPLIED>
  <!ATTLIST ROW Library_Reference CDATA #IMPLIED>
  <!ATTLIST ROW LibRef CDATA #IMPLIED>
  <!ATTLIST ROW LogicalDesignator CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_1 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_2 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number_1 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number_2 CDATA #IMPLIED>
  <!ATTLIST ROW Model_Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Model_Signal_Integrity CDATA #IMPLIED>
  <!ATTLIST ROW Model_Simulation CDATA #IMPLIED>
  <!ATTLIST ROW Models CDATA #IMPLIED>
  <!ATTLIST ROW ModifiedDate CDATA #IMPLIED>
  <!ATTLIST ROW Note CDATA #IMPLIED>
  <!ATTLIST ROW Organization CDATA #IMPLIED>
  <!ATTLIST ROW PackageDescription CDATA #IMPLIED>
  <!ATTLIST ROW PackageReference CDATA #IMPLIED>
  <!ATTLIST ROW PackageTopMarking CDATA #IMPLIED>
  <!ATTLIST ROW PackageVersion CDATA #IMPLIED>
  <!ATTLIST ROW PartNumber CDATA #IMPLIED>
  <!ATTLIST ROW PartType CDATA #IMPLIED>
  <!ATTLIST ROW PCB3D CDATA #IMPLIED>
  <!ATTLIST ROW PhysicalPath CDATA #IMPLIED>
  <!ATTLIST ROW PinCount CDATA #IMPLIED>
  <!ATTLIST ROW Pins CDATA #IMPLIED>
  <!ATTLIST ROW Project CDATA #IMPLIED>
  <!ATTLIST ROW ProjectName CDATA #IMPLIED>
  <!ATTLIST ROW Published CDATA #IMPLIED>
  <!ATTLIST ROW Publisher CDATA #IMPLIED>
  <!ATTLIST ROW Quantity CDATA #IMPLIED>
  <!ATTLIST ROW Revision CDATA #IMPLIED>
  <!ATTLIST ROW RevisionGUID CDATA #IMPLIED>
  <!ATTLIST ROW RoHS CDATA #IMPLIED>
  <!ATTLIST ROW Rule CDATA #IMPLIED>
  <!ATTLIST ROW SheetNumber CDATA #IMPLIED>
  <!ATTLIST ROW SheetTotal CDATA #IMPLIED>
  <!ATTLIST ROW Signal_Integrity CDATA #IMPLIED>
  <!ATTLIST ROW Simulation CDATA #IMPLIED>
  <!ATTLIST ROW SourceLibraryName CDATA #IMPLIED>
  <!ATTLIST ROW Sub_Parts CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_2 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Currency_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Currency_2 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Order_Qty_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Order_Qty_2 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Part_Number_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Part_Number_2 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Stock_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Stock_2 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Subtotal_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Subtotal_2 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Unit_Price_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Unit_Price_2 CDATA #IMPLIED>
  <!ATTLIST ROW Time CDATA #IMPLIED>
  <!ATTLIST ROW Title CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdName CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdPath CDATA #IMPLIED>
  <!ATTLIST ROW Value CDATA #IMPLIED>
  <!ATTLIST ROW Variant CDATA #IMPLIED>
  <!ATTLIST ROW VaultGUID CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="Address1" Caption="Address1" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="100"></COLUMN>
    <COLUMN Name="Address2" Caption="Address2" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="100"></COLUMN>
    <COLUMN Name="Address3" Caption="Address3" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="100"></COLUMN>
    <COLUMN Name="Address4" Caption="Address4" Index="3" BandIndex="0" RowIndex="0" ColIndex="3" Width="100"></COLUMN>
    <COLUMN Name="Application_BuildNumber" Caption="Application_BuildNumber" Index="4" BandIndex="0" RowIndex="0" ColIndex="4" Width="100"></COLUMN>
    <COLUMN Name="ApprovedBy" Caption="ApprovedBy" Index="5" BandIndex="0" RowIndex="0" ColIndex="5" Width="100"></COLUMN>
    <COLUMN Name="Author" Caption="Author" Index="6" BandIndex="0" RowIndex="0" ColIndex="6" Width="100"></COLUMN>
    <COLUMN Name="CheckedBy" Caption="CheckedBy" Index="7" BandIndex="0" RowIndex="0" ColIndex="7" Width="100"></COLUMN>
    <COLUMN Name="Code_IPC" Caption="Code_IPC" Index="8" BandIndex="0" RowIndex="0" ColIndex="8" Width="100"></COLUMN>
    <COLUMN Name="Code_JEDEC" Caption="Code_JEDEC" Index="9" BandIndex="0" RowIndex="0" ColIndex="9" Width="100"></COLUMN>
    <COLUMN Name="Comment" Caption="Comment" Index="10" BandIndex="0" RowIndex="0" ColIndex="10" Width="100"></COLUMN>
    <COLUMN Name="CompanyName" Caption="CompanyName" Index="11" BandIndex="0" RowIndex="0" ColIndex="11" Width="100"></COLUMN>
    <COLUMN Name="Component_Kind" Caption="Component Kind" Index="12" BandIndex="0" RowIndex="0" ColIndex="12" Width="100"></COLUMN>
    <COLUMN Name="ComponentKind" Caption="ComponentKind" Index="13" BandIndex="0" RowIndex="0" ColIndex="13" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink1Description" Caption="ComponentLink1Description" Index="14" BandIndex="0" RowIndex="0" ColIndex="14" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink1URL" Caption="ComponentLink1URL" Index="15" BandIndex="0" RowIndex="0" ColIndex="15" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink2Description" Caption="ComponentLink2Description" Index="16" BandIndex="0" RowIndex="0" ColIndex="16" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink2URL" Caption="ComponentLink2URL" Index="17" BandIndex="0" RowIndex="0" ColIndex="17" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink3Description" Caption="ComponentLink3Description" Index="18" BandIndex="0" RowIndex="0" ColIndex="18" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink3URL" Caption="ComponentLink3URL" Index="19" BandIndex="0" RowIndex="0" ColIndex="19" Width="100"></COLUMN>
    <COLUMN Name="CompType" Caption="CompType" Index="20" BandIndex="0" RowIndex="0" ColIndex="20" Width="100"></COLUMN>
    <COLUMN Name="CurrentDate" Caption="CurrentDate" Index="21" BandIndex="0" RowIndex="0" ColIndex="21" Width="100"></COLUMN>
    <COLUMN Name="CurrentTime" Caption="CurrentTime" Index="22" BandIndex="0" RowIndex="0" ColIndex="22" Width="100"></COLUMN>
    <COLUMN Name="DatasheetDocument" Caption="DatasheetDocument" Index="23" BandIndex="0" RowIndex="0" ColIndex="23" Width="100"></COLUMN>
    <COLUMN Name="DatasheetVersion" Caption="DatasheetVersion" Index="24" BandIndex="0" RowIndex="0" ColIndex="24" Width="100"></COLUMN>
    <COLUMN Name="Date" Caption="Date" Index="25" BandIndex="0" RowIndex="0" ColIndex="25" Width="100"></COLUMN>
    <COLUMN Name="Description" Caption="Description" Index="26" BandIndex="0" RowIndex="0" ColIndex="26" Width="100"></COLUMN>
    <COLUMN Name="Designator" Caption="Designator" Index="27" BandIndex="0" RowIndex="0" ColIndex="27" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_Mil_" Caption="Designator-X&#40;Mil&#41;" Index="28" BandIndex="0" RowIndex="0" ColIndex="28" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_mm_" Caption="Designator-X&#40;mm&#41;" Index="29" BandIndex="0" RowIndex="0" ColIndex="29" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_Mil_" Caption="Designator-Y&#40;Mil&#41;" Index="30" BandIndex="0" RowIndex="0" ColIndex="30" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_mm_" Caption="Designator-Y&#40;mm&#41;" Index="31" BandIndex="0" RowIndex="0" ColIndex="31" Width="100"></COLUMN>
    <COLUMN Name="DesignItemId" Caption="DesignItemId" Index="32" BandIndex="0" RowIndex="0" ColIndex="32" Width="100"></COLUMN>
    <COLUMN Name="Document" Caption="Document" Index="33" BandIndex="0" RowIndex="0" ColIndex="33" Width="100"></COLUMN>
    <COLUMN Name="DocumentFullPathAndName" Caption="DocumentFullPathAndName" Index="34" BandIndex="0" RowIndex="0" ColIndex="34" Width="100"></COLUMN>
    <COLUMN Name="DocumentName" Caption="DocumentName" Index="35" BandIndex="0" RowIndex="0" ColIndex="35" Width="100"></COLUMN>
    <COLUMN Name="DocumentNumber" Caption="DocumentNumber" Index="36" BandIndex="0" RowIndex="0" ColIndex="36" Width="100"></COLUMN>
    <COLUMN Name="DrawnBy" Caption="DrawnBy" Index="37" BandIndex="0" RowIndex="0" ColIndex="37" Width="100"></COLUMN>
    <COLUMN Name="Engineer" Caption="Engineer" Index="38" BandIndex="0" RowIndex="0" ColIndex="38" Width="100"></COLUMN>
    <COLUMN Name="Footprint" Caption="Footprint" Index="39" BandIndex="0" RowIndex="0" ColIndex="39" Width="100"></COLUMN>
    <COLUMN Name="Frequence" Caption="Frequence" Index="40" BandIndex="0" RowIndex="0" ColIndex="40" Width="100"></COLUMN>
    <COLUMN Name="Height_Mil_" Caption="Height&#40;Mil&#41;" Index="41" BandIndex="0" RowIndex="0" ColIndex="41" Width="100"></COLUMN>
    <COLUMN Name="Height_mm_" Caption="Height&#40;mm&#41;" Index="42" BandIndex="0" RowIndex="0" ColIndex="42" Width="100"></COLUMN>
    <COLUMN Name="Ibis_Model" Caption="Ibis Model" Index="43" BandIndex="0" RowIndex="0" ColIndex="43" Width="100"></COLUMN>
    <COLUMN Name="ImagePath" Caption="ImagePath" Index="44" BandIndex="0" RowIndex="0" ColIndex="44" Width="100"></COLUMN>
    <COLUMN Name="Index" Caption="Index" Index="45" BandIndex="0" RowIndex="0" ColIndex="45" Width="100"></COLUMN>
    <COLUMN Name="ItemGUID" Caption="ItemGUID" Index="46" BandIndex="0" RowIndex="0" ColIndex="46" Width="100"></COLUMN>
    <COLUMN Name="LatestRevisionDate" Caption="LatestRevisionDate" Index="47" BandIndex="0" RowIndex="0" ColIndex="47" Width="100"></COLUMN>
    <COLUMN Name="LatestRevisionNote" Caption="LatestRevisionNote" Index="48" BandIndex="0" RowIndex="0" ColIndex="48" Width="100"></COLUMN>
    <COLUMN Name="Library_Name" Caption="Library Name" Index="49" BandIndex="0" RowIndex="0" ColIndex="49" Width="100"></COLUMN>
    <COLUMN Name="Library_Reference" Caption="Library Reference" Index="50" BandIndex="0" RowIndex="0" ColIndex="50" Width="100"></COLUMN>
    <COLUMN Name="LibRef" Caption="LibRef" Index="51" BandIndex="0" RowIndex="0" ColIndex="51" Width="100"></COLUMN>
    <COLUMN Name="LogicalDesignator" Caption="LogicalDesignator" Index="52" BandIndex="0" RowIndex="0" ColIndex="52" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer" Caption="Manufacturer" Index="53" BandIndex="0" RowIndex="0" ColIndex="53" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_1" Caption="Manufacturer 1" Index="54" BandIndex="0" RowIndex="0" ColIndex="54" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_2" Caption="Manufacturer 2" Index="55" BandIndex="0" RowIndex="0" ColIndex="55" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number_1" Caption="Manufacturer Part Number 1" Index="56" BandIndex="0" RowIndex="0" ColIndex="56" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number_2" Caption="Manufacturer Part Number 2" Index="57" BandIndex="0" RowIndex="0" ColIndex="57" Width="100"></COLUMN>
    <COLUMN Name="Model_Footprint" Caption="Model:Footprint" Index="58" BandIndex="0" RowIndex="0" ColIndex="58" Width="100"></COLUMN>
    <COLUMN Name="Model_Signal_Integrity" Caption="Model:Signal Integrity" Index="59" BandIndex="0" RowIndex="0" ColIndex="59" Width="100"></COLUMN>
    <COLUMN Name="Model_Simulation" Caption="Model:Simulation" Index="60" BandIndex="0" RowIndex="0" ColIndex="60" Width="100"></COLUMN>
    <COLUMN Name="Models" Caption="Models" Index="61" BandIndex="0" RowIndex="0" ColIndex="61" Width="100"></COLUMN>
    <COLUMN Name="ModifiedDate" Caption="ModifiedDate" Index="62" BandIndex="0" RowIndex="0" ColIndex="62" Width="100"></COLUMN>
    <COLUMN Name="Note" Caption="Note" Index="63" BandIndex="0" RowIndex="0" ColIndex="63" Width="100"></COLUMN>
    <COLUMN Name="Organization" Caption="Organization" Index="64" BandIndex="0" RowIndex="0" ColIndex="64" Width="100"></COLUMN>
    <COLUMN Name="PackageDescription" Caption="PackageDescription" Index="65" BandIndex="0" RowIndex="0" ColIndex="65" Width="100"></COLUMN>
    <COLUMN Name="PackageReference" Caption="PackageReference" Index="66" BandIndex="0" RowIndex="0" ColIndex="66" Width="100"></COLUMN>
    <COLUMN Name="PackageTopMarking" Caption="PackageTopMarking" Index="67" BandIndex="0" RowIndex="0" ColIndex="67" Width="100"></COLUMN>
    <COLUMN Name="PackageVersion" Caption="PackageVersion" Index="68" BandIndex="0" RowIndex="0" ColIndex="68" Width="100"></COLUMN>
    <COLUMN Name="PartNumber" Caption="PartNumber" Index="69" BandIndex="0" RowIndex="0" ColIndex="69" Width="100"></COLUMN>
    <COLUMN Name="PartType" Caption="PartType" Index="70" BandIndex="0" RowIndex="0" ColIndex="70" Width="100"></COLUMN>
    <COLUMN Name="PCB3D" Caption="PCB3D" Index="71" BandIndex="0" RowIndex="0" ColIndex="71" Width="100"></COLUMN>
    <COLUMN Name="PhysicalPath" Caption="PhysicalPath" Index="72" BandIndex="0" RowIndex="0" ColIndex="72" Width="100"></COLUMN>
    <COLUMN Name="PinCount" Caption="PinCount" Index="73" BandIndex="0" RowIndex="0" ColIndex="73" Width="100"></COLUMN>
    <COLUMN Name="Pins" Caption="Pins" Index="74" BandIndex="0" RowIndex="0" ColIndex="74" Width="100"></COLUMN>
    <COLUMN Name="Project" Caption="Project" Index="75" BandIndex="0" RowIndex="0" ColIndex="75" Width="100"></COLUMN>
    <COLUMN Name="ProjectName" Caption="ProjectName" Index="76" BandIndex="0" RowIndex="0" ColIndex="76" Width="100"></COLUMN>
    <COLUMN Name="Published" Caption="Published" Index="77" BandIndex="0" RowIndex="0" ColIndex="77" Width="100"></COLUMN>
    <COLUMN Name="Publisher" Caption="Publisher" Index="78" BandIndex="0" RowIndex="0" ColIndex="78" Width="100"></COLUMN>
    <COLUMN Name="Quantity" Caption="Quantity" Index="79" BandIndex="0" RowIndex="0" ColIndex="79" Width="100"></COLUMN>
    <COLUMN Name="Revision" Caption="Revision" Index="80" BandIndex="0" RowIndex="0" ColIndex="80" Width="100"></COLUMN>
    <COLUMN Name="RevisionGUID" Caption="RevisionGUID" Index="81" BandIndex="0" RowIndex="0" ColIndex="81" Width="100"></COLUMN>
    <COLUMN Name="RoHS" Caption="RoHS" Index="82" BandIndex="0" RowIndex="0" ColIndex="82" Width="100"></COLUMN>
    <COLUMN Name="Rule" Caption="Rule" Index="83" BandIndex="0" RowIndex="0" ColIndex="83" Width="100"></COLUMN>
    <COLUMN Name="SheetNumber" Caption="SheetNumber" Index="84" BandIndex="0" RowIndex="0" ColIndex="84" Width="100"></COLUMN>
    <COLUMN Name="SheetTotal" Caption="SheetTotal" Index="85" BandIndex="0" RowIndex="0" ColIndex="85" Width="100"></COLUMN>
    <COLUMN Name="Signal_Integrity" Caption="Signal Integrity" Index="86" BandIndex="0" RowIndex="0" ColIndex="86" Width="100"></COLUMN>
    <COLUMN Name="Simulation" Caption="Simulation" Index="87" BandIndex="0" RowIndex="0" ColIndex="87" Width="100"></COLUMN>
    <COLUMN Name="SourceLibraryName" Caption="SourceLibraryName" Index="88" BandIndex="0" RowIndex="0" ColIndex="88" Width="100"></COLUMN>
    <COLUMN Name="Sub_Parts" Caption="Sub-Parts" Index="89" BandIndex="0" RowIndex="0" ColIndex="89" Width="100"></COLUMN>
    <COLUMN Name="Supplier_1" Caption="Supplier 1" Index="90" BandIndex="0" RowIndex="0" ColIndex="90" Width="100"></COLUMN>
    <COLUMN Name="Supplier_2" Caption="Supplier 2" Index="91" BandIndex="0" RowIndex="0" ColIndex="91" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Currency_1" Caption="Supplier Currency 1" Index="92" BandIndex="0" RowIndex="0" ColIndex="92" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Currency_2" Caption="Supplier Currency 2" Index="93" BandIndex="0" RowIndex="0" ColIndex="93" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Order_Qty_1" Caption="Supplier Order Qty 1" Index="94" BandIndex="0" RowIndex="0" ColIndex="94" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Order_Qty_2" Caption="Supplier Order Qty 2" Index="95" BandIndex="0" RowIndex="0" ColIndex="95" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Part_Number_1" Caption="Supplier Part Number 1" Index="96" BandIndex="0" RowIndex="0" ColIndex="96" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Part_Number_2" Caption="Supplier Part Number 2" Index="97" BandIndex="0" RowIndex="0" ColIndex="97" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Stock_1" Caption="Supplier Stock 1" Index="98" BandIndex="0" RowIndex="0" ColIndex="98" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Stock_2" Caption="Supplier Stock 2" Index="99" BandIndex="0" RowIndex="0" ColIndex="99" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Subtotal_1" Caption="Supplier Subtotal 1" Index="100" BandIndex="0" RowIndex="0" ColIndex="100" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Subtotal_2" Caption="Supplier Subtotal 2" Index="101" BandIndex="0" RowIndex="0" ColIndex="101" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Unit_Price_1" Caption="Supplier Unit Price 1" Index="102" BandIndex="0" RowIndex="0" ColIndex="102" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Unit_Price_2" Caption="Supplier Unit Price 2" Index="103" BandIndex="0" RowIndex="0" ColIndex="103" Width="100"></COLUMN>
    <COLUMN Name="Time" Caption="Time" Index="104" BandIndex="0" RowIndex="0" ColIndex="104" Width="100"></COLUMN>
    <COLUMN Name="Title" Caption="Title" Index="105" BandIndex="0" RowIndex="0" ColIndex="105" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdName" Caption="UniqueIdName" Index="106" BandIndex="0" RowIndex="0" ColIndex="106" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdPath" Caption="UniqueIdPath" Index="107" BandIndex="0" RowIndex="0" ColIndex="107" Width="100"></COLUMN>
    <COLUMN Name="Value" Caption="Value" Index="108" BandIndex="0" RowIndex="0" ColIndex="108" Width="100"></COLUMN>
    <COLUMN Name="Variant" Caption="Variant" Index="109" BandIndex="0" RowIndex="0" ColIndex="109" Width="100"></COLUMN>
    <COLUMN Name="VaultGUID" Caption="VaultGUID" Index="110" BandIndex="0" RowIndex="0" ColIndex="110" Width="100"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW Address1="" Address2="" Address3="" Address4="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" Code_IPC="" Code_JEDEC="" Comment="Socket" CompanyName="" Component_Kind="Standard" ComponentKind="0" ComponentLink1Description="" ComponentLink1URL="" ComponentLink2Description="" ComponentLink2URL="" ComponentLink3Description="" ComponentLink3URL="" CompType="" CurrentDate="18.10.2014" CurrentTime="0:14:11" DatasheetDocument="" DatasheetVersion="" Date="" Description="Socket" Designator="+U" Designator_X_Mil_="990" Designator_X_mm_="25.146" Designator_Y_Mil_="4910" Designator_Y_mm_="124.714" DesignItemId="Socket" Document="E:&#92;!&#92;Projects&#92;Radio&#92;QuasarARM&#92;ADesignerProject&#92;Quasar ARM&#92;Power block.SchDoc" DocumentFullPathAndName="E:&#92;!&#92;Projects&#92;Radio&#92;QuasarARM&#92;ADesignerProject&#92;Quasar ARM&#92;Power block.SchDoc" DocumentName="Power block.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="PIN1" Frequence="" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="1" ItemGUID="" LatestRevisionDate="17-Jul-2002" LatestRevisionNote="Re-released for DXP Platform." Library_Name="Miscellaneous Connectors.IntLib" Library_Reference="Socket" LibRef="Socket" LogicalDesignator="+U" Manufacturer="" Manufacturer_1="" Manufacturer_2="" Manufacturer_Part_Number_1="" Manufacturer_Part_Number_2="" Model_Footprint="Connector; Socket" Model_Signal_Integrity="" Model_Simulation="" Models="2" ModifiedDate="12.10.2014" Note="" Organization="" PackageDescription="" PackageReference="" PackageTopMarking="" PackageVersion="" PartNumber="" PartType="Socket" PCB3D="" PhysicalPath="Power block" PinCount="" Pins="1" Project="E:&#92;!&#92;Projects&#92;Radio&#92;QuasarARM&#92;ADesignerProject&#92;Quasar ARM&#92;Quasar ARM.PrjPcb" ProjectName="Quasar ARM.PrjPcb" Published="" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" RoHS="" Rule="" SheetNumber="" SheetTotal="" Signal_Integrity="Connector" Simulation="" SourceLibraryName="Miscellaneous Connectors.IntLib" Sub_Parts="1" Supplier_1="" Supplier_2="" Supplier_Currency_1="" Supplier_Currency_2="" Supplier_Order_Qty_1="" Supplier_Order_Qty_2="" Supplier_Part_Number_1="" Supplier_Part_Number_2="" Supplier_Stock_1="" Supplier_Stock_2="" Supplier_Subtotal_1="" Supplier_Subtotal_2="" Supplier_Unit_Price_1="" Supplier_Unit_Price_2="" Time="" Title="" UniqueIdName="SWNRNSLE" UniqueIdPath="" Value="" Variant="" VaultGUID=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" Code_IPC="" Code_JEDEC="" Comment="Socket" CompanyName="" Component_Kind="Standard" ComponentKind="0" ComponentLink1Description="" ComponentLink1URL="" ComponentLink2Description="" ComponentLink2URL="" ComponentLink3Description="" ComponentLink3URL="" CompType="" CurrentDate="18.10.2014" CurrentTime="0:14:11" DatasheetDocument="" DatasheetVersion="" Date="" Description="Socket" Designator="-U" Designator_X_Mil_="990" Designator_X_mm_="25.146" Designator_Y_Mil_="4310" Designator_Y_mm_="109.474" DesignItemId="Socket" Document="E:&#92;!&#92;Projects&#92;Radio&#92;QuasarARM&#92;ADesignerProject&#92;Quasar ARM&#92;Power block.SchDoc" DocumentFullPathAndName="E:&#92;!&#92;Projects&#92;Radio&#92;QuasarARM&#92;ADesignerProject&#92;Quasar ARM&#92;Power block.SchDoc" DocumentName="Power block.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="PIN1" Frequence="" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="2" ItemGUID="" LatestRevisionDate="17-Jul-2002" LatestRevisionNote="Re-released for DXP Platform." Library_Name="Miscellaneous Connectors.IntLib" Library_Reference="Socket" LibRef="Socket" LogicalDesignator="-U" Manufacturer="" Manufacturer_1="" Manufacturer_2="" Manufacturer_Part_Number_1="" Manufacturer_Part_Number_2="" Model_Footprint="Connector; Socket" Model_Signal_Integrity="" Model_Simulation="" Models="2" ModifiedDate="12.10.2014" Note="" Organization="" PackageDescription="" PackageReference="" PackageTopMarking="" PackageVersion="" PartNumber="" PartType="Socket" PCB3D="" PhysicalPath="Power block" PinCount="" Pins="1" Project="E:&#92;!&#92;Projects&#92;Radio&#92;QuasarARM&#92;ADesignerProject&#92;Quasar ARM&#92;Quasar ARM.PrjPcb" ProjectName="Quasar ARM.PrjPcb" Published="" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" RoHS="" Rule="" SheetNumber="" SheetTotal="" Signal_Integrity="Connector" Simulation="" SourceLibraryName="Miscellaneous Connectors.IntLib" Sub_Parts="1" Supplier_1="" Supplier_2="" Supplier_Currency_1="" Supplier_Currency_2="" Supplier_Order_Qty_1="" Supplier_Order_Qty_2="" Supplier_Part_Number_1="" Supplier_Part_Number_2="" Supplier_Stock_1="" Supplier_Stock_2="" Supplier_Subtotal_1="" Supplier_Subtotal_2="" Supplier_Unit_Price_1="" Supplier_Unit_Price_2="" Time="" Title="" UniqueIdName="AQVFHWNI" UniqueIdPath="" Value="" Variant="" VaultGUID=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" Code_IPC="" Code_JEDEC="" Comment="8,0 MHz" CompanyName="" Component_Kind="Standard" ComponentKind="0" ComponentLink1Description="" ComponentLink1URL="" ComponentLink2Description="" ComponentLink2URL="" ComponentLink3Description="" ComponentLink3URL="" CompType="" CurrentDate="18.10.2014" CurrentTime="0:14:11" DatasheetDocument="" DatasheetVersion="" Date="" Description="Crystal Oscillator" Designator="BQ1" Designator_X_Mil_="1980" Designator_X_mm_="50.292" Designator_Y_Mil_="2710" Designator_Y_mm_="68.834" DesignItemId="XTAL" Document="E:&#92;!&#92;Projects&#92;Radio&#92;QuasarARM&#92;ADesignerProject&#92;Quasar ARM&#92;Microcontroller block.SchDoc" DocumentFullPathAndName="E:&#92;!&#92;Projects&#92;Radio&#92;QuasarARM&#92;ADesignerProject&#92;Quasar ARM&#92;Microcontroller block.SchDoc" DocumentName="Microcontroller block.SchDoc" DocumentNumber="" DrawnBy="" Engineer="" Footprint="HC-49/U3H &#40;low profile&#41;" Frequence="8,0 MHz" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="3" ItemGUID="" LatestRevisionDate="17-Jul-2002" LatestRevisionNote="Re-released for DXP Platform." Library_Name="Quasar ARM.SCHLIB" Library_Reference="XTAL" LibRef="XTAL" LogicalDesignator="BQ1" Manufacturer="" Manufacturer_1="" Manufacturer_2="" Manufacturer_Part_Number_1="" Manufacturer_Part_Number_2="" Model_Footprint="QUARTZ CRYSTALS HC-49/U3H &#40;low profile&#41;" Model_Signal_Integrity="" Model_Simulation="" Models="1" ModifiedDate="19.09.2014" Note="" Organization="" PackageDescription="Crystal, Thru-Hole; 2 Leads; Body 3.1 x 8.2 mm &#40;Dia.xH&#41;" PackageReference="R38" PackageTopMarking="" PackageVersion="" PartNumber="" PartType="8,0 MHz" PCB3D="" PhysicalPath="Microcontroller block" PinCount="" Pins="2" Project="E:&#92;!&#92;Projects&#92;Radio&#92;QuasarARM&#92;ADesignerProject&#92;Quasar ARM&#92;Quasar ARM.PrjPcb" ProjectName="Quasar ARM.PrjPcb" Published="8-Jun-2000" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" RoHS="" Rule="" SheetNumber="" SheetTotal="" Signal_Integrity="" Simulation="" SourceLibraryName="Quasar ARM.SCHLIB" Sub_Parts="1" Supplier_1="" Supplier_2="" Supplier_Currency_1="" Supplier_Currency_2="" Supplier_Order_Qty_1="" Supplier_Order_Qty_2="" Supplier_Part_Number_1="" Supplier_Part_Number_2="" Supplier_Stock_1="" Supplier_Stock_2="" Supplier_Subtotal_1="" Supplier_Subtotal_2="" Supplier_Unit_Price_1="" Supplier_Unit_Price_2="" Time="" Title="" UniqueIdName="XWQETCKR" UniqueIdPath="" Value="" Variant="" VaultGUID=""></ROW>